server:
  port: 8001

spring:
  profiles:
    active: dev  # 开发模式
  application:
    name: nn-webfont
  mail:
    host: smtp.163.com
    username: duizhang627@163.com
    password: FTCXIEVFUMEGRLUS
    test-connection: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss



jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: webfont
  key:
    emailVerifyCode: 'email:verifyCode'
    articleReadCount: 'article:readCount'
    articleLikeRecord: 'article:likeRecord'
    articleLikeNumber: 'article:likeNumber'
    articleStoreNumber: 'article:storeNumber'
    articleUpdateSet: 'article:updateSet'
  expire:
    fiveMin: 300 # 5分钟

qiniu:
  accessKey: cQlOrwEvBPZJCNI5Lg6CGSJ1Hj3ivkKbTeXHO_4Y
  secretKey: de0rNkuTiZfwhYFeC2_QcA7RZ8EsTQMTCFkeuev3
  notnullBucket: 'notnull-project' # 空间名管理
  folderName: 'webfont' # 文件夹管理
  domainName: 'resource.duizhangz.cn' # 域名管理